server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=5s ipv6=off;

    set $backend_upstream http://backend:8000;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /buildings {
        proxy_pass $backend_upstream;
    }

    location /path {
        proxy_pass $backend_upstream;
    }

    location /health {
        proxy_pass $backend_upstream;
    }
}
